# Generated by Django 3.0.2 on 2020-01-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
